name: Publish Package

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: |
          cd packages/vultr-types && pnpm build
          cd ../tailportal && pnpm build

      - name: Publish stable release
        if: startsWith(github.ref, 'refs/tags/v')
        run: cd packages/tailportal && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish beta release
        if: github.ref == 'refs/heads/main'
        run: |
          cd packages/tailportal
          # Generate beta version with timestamp
          BETA_VERSION=$(node -p "require('./package.json').version + '-beta.' + Date.now()")
          npm version $BETA_VERSION --no-git-tag-version
          npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  test-installation:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Test stable installation
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          npm install -g tailportal
          tailportal --help
          npm uninstall -g tailportal

      - name: Test beta installation
        if: github.ref == 'refs/heads/main'
        run: |
          npm install -g tailportal@beta
          tailportal --help
          npm uninstall -g tailportal